### ISSUE TITLE
已经结束的学术报告仍被选中

### ISSUE THREAD

**Issue by MoreanP** [Indigo6/USTC_xsbg_monitor#1]
一个小bug，如果学术报告首页里有没被选过，但是时间已经结束的学术报告，也会被选中。没法退选，最后只能脚本退。建议加一个check报告时间的修改。

**Comment by Indigo6** [comment]
谢谢！确实有这个问题，最近比较忙，抽时间把筛选条件补充完整

**Comment by Indigo6** [comment]
> 一个小bug，如果学术报告首页里有没被选过，但是时间已经结束的学术报告，也会被选中。没法退选，最后只能脚本退。建议加一个check报告时间的修改。
已解决， [#f21cbc6bcbd9a7e9055498f2217d627f7ea6c1b0](https://github.com/Indigo6/USTC_xsbg_monitor/commit/f21cbc6bcbd9a7e9055498f2217d627f7ea6c1b0)

**Comment by Indigo6** [comment]
> 一个小bug，如果学术报告首页里有没被选过，但是时间已经结束的学术报告，也会被选中。没法退选，最后只能脚本退。建议加一个check报告时间的修改。

已解决， [#f21cbc6bcbd9a7e9055498f2217d627f7ea6c1b0](https://github.com/Indigo6/USTC_xsbg_monitor/commit/f21cbc6bcbd9a7e9055498f2217d627f7ea6c1b0)

**Comment by MoreanP** [comment]
![image](https://user-images.githubusercontent.com/37109784/143020600-738e41ff-f098-4e92-bf19-b2d24d52113c.png)
这样的话，如果今天是2021/11/23，有个2021/12/1的报告，也会判断为已过期
